### ISSUE TITLE
TypeError: '<' not supported between instances of 'int' and 'NoneType'

### ISSUE THREAD

**Issue by kN6jq** [ntestoc3/norecon#1]
![image](https://user-images.githubusercontent.com/27048404/95339382-975eba00-08e6-11eb-978c-16387faab36b.png)

oh! i can't run it

**Comment by ntestoc3** [comment]
-v参数需要指定整数

**Comment by ntestoc3** [comment]
https://github.com/ntestoc3/norecon/commit/86470a1b2f2ff0ea5d79c709f5bff0d1484f0a90 增加指定-v参数时的默认值为1
